# Generated by Django 3.1.5 on 2021-01-07 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='authod',
            new_name='author',
        ),
    ]
